002 branding
Joshua-Noble-Dev/Group3-Frontend pull request #11
Opened 2024-07-24 10:14 UTC by Katiemcallister

2024-07-24 10:33 UTC, shaunganley requested changes

2024-07-24 10:33 UTC, shaunganley commented on .vscode/launch.json
> +            "url": "http://localhost:8080",
doesn't look right for frontend URL

2024-07-24 10:33 UTC, shaunganley commented on src/app.ts
>  });
think you can remove this as you've added the part below

2024-07-24 10:33 UTC, shaunganley commented on src/app.ts
> +app.get('/jobRoles', getAllJobRoles);
by adding all of the job role stuff in this branch we can't progress the branding ticket until the job roles ticket is complete. I recommend removing all the job roles stuff and just make this PR about the branding

2024-07-24 10:33 UTC, shaunganley commented on views/homepage.html
> +        <nav class="header">
move this section to a header.html file and import it here so we can reuse on all pages

2024-07-24 10:33 UTC, shaunganley commented on views/homepage.html
> +                            <div class="footer-basic">
move this section to a footer.html file and import it here so we can reuse on all pages

2024-07-26 06:53 UTC, shaunganley approved these changes

2024-07-26 06:57 UTC, BenjaminBrashaw approved these changes

2024-07-26 09:45 UTC, merged